project:
  type: website
  output-dir: "docs"
  render:
  - "*.qmd"
  - "*.ipynb"
  - "README.md"

#execute:
#  freeze: auto

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: README.md 

  sidebar:
    contents: notebook         
