project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!drafts/"
execute:
  freeze: auto

website:
  repo-url: https://github.com/espm-288/cloud-native-geo-cboettig
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - file: index.qmd
        icon: house
        text: About
      - section: Resources
        contents:
          - text: Catalog of catalogs
            icon: book
            href: https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/schmidtDSE/biodiversity-catalog/main/stac/v1/catalog.json?.language=en
          - text: Codespaces
            icon: pc-horizontal
            href: https://codespaces.new/espm-157/nasa-topst-env-justice?quickstart=1
          - text: JuypterHub
            icon: cloud
            href: https://openscapes.2i2c.cloud/
      - section: Recipes
        contents:
          - text: Introduction
            icon: play-btn
            href: contents/intro.qmd
      - section: Background
        contents:
          - text: Portable Environments
            href: contents/computing-environment.qmd
  page-footer:
    right: 
      - icon: github
        href: https://github.com/boettiger-lab/nasa-topst-env-justice
      - icon: globe-americas 
        href: https://carlboettiger.info  

          
